"""Add financial_profile table

Revision ID: 22c4b48d0439
Revises: b99dfcc7fd09
Create Date: 2026-03-09 19:56:17.410474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22c4b48d0439'
down_revision: Union[str, Sequence[str], None] = 'b99dfcc7fd09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('financial_year', sa.String(), nullable=True),
    sa.Column('total_income', sa.Float(), nullable=True),
    sa.Column('total_deductions', sa.Float(), nullable=True),
    sa.Column('total_tds', sa.Float(), nullable=True),
    sa.Column('calculated_old_tax', sa.Float(), nullable=True),
    sa.Column('calculated_new_tax', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_profiles_id'), 'financial_profiles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_financial_profiles_id'), table_name='financial_profiles')
    op.drop_table('financial_profiles')
    # ### end Alembic commands ###
