"""
AI Post-Generation Validator — Golden Rule Enforcement

Ensures that no AI-generated response contains tax figures that
were NOT produced by the deterministic tax engine.

Per project rules: "The AI layer (Gemini/GPT) NEVER produces tax figures.
All rupee amounts in any API response MUST be sourced from engine/tax_engine.py."
"""

import re
from typing import Dict, Any, List, Optional


# Pattern to match rupee amounts in text: ₹1,23,456 or Rs. 1,23,456 or INR 123456
RUPEE_PATTERN = re.compile(
    r'(?:₹|Rs\.?|INR)\s*'           # Currency symbol
    r'(\d[\d,]*(?:\.\d{1,2})?)',     # Amount with optional commas and decimals
    re.IGNORECASE
)

# Also match plain amounts with Indian notation like "1,23,456" when near tax-related words
TAX_CONTEXT_PATTERN = re.compile(
    r'(?:tax|cess|surcharge|deduction|rebate|liability|payable|refund|income|salary|tds)'
    r'[^₹\d]{0,40}'                  # Up to 40 chars between keyword and number
    r'(\d{1,3}(?:,\d{2,3})*(?:\.\d{1,2})?)',   # Number with commas
    re.IGNORECASE
)


def _parse_amount(amount_str: str) -> float:
    """Parse an Indian-formatted amount string to float."""
    cleaned = amount_str.replace(",", "").strip()
    try:
        return float(cleaned)
    except ValueError:
        return -1.0


def extract_amounts_from_text(text: str) -> List[float]:
    """Extract all rupee amounts mentioned in AI-generated text."""
    amounts = set()
    
    # Match explicit rupee symbols
    for match in RUPEE_PATTERN.finditer(text):
        val = _parse_amount(match.group(1))
        if val > 0:
            amounts.add(val)
    
    # Match amounts near tax keywords
    for match in TAX_CONTEXT_PATTERN.finditer(text):
        val = _parse_amount(match.group(1))
        if val > 0:
            amounts.add(val)
    
    return list(amounts)


def validate_response(
    ai_text: str,
    engine_output: Optional[Dict[str, Any]] = None,
    tolerance: float = 1.0
) -> Dict[str, Any]:
    """
    Validate an AI-generated response against engine output.
    
    Args:
        ai_text: The text generated by the AI (GPT/Ollama/Gemini).
        engine_output: Dict from tax engine containing authoritative figures.
        tolerance: Allowed difference in rupees (to handle rounding).
    
    Returns:
        Dict with:
          - is_valid: True if no unauthorized figures found
          - flagged_amounts: List of amounts in text not matching engine output
          - engine_amounts: Set of authorized amounts from engine
          - warning: Human-readable warning if validation fails
    """
    ai_amounts = extract_amounts_from_text(ai_text)
    
    # If no engine output provided, flag any monetary amounts as unvalidated
    if engine_output is None:
        if ai_amounts:
            return {
                "is_valid": False,
                "flagged_amounts": ai_amounts,
                "engine_amounts": [],
                "warning": (
                    f"AI response contains {len(ai_amounts)} monetary figure(s) "
                    f"but no engine output was provided for validation."
                )
            }
        return {"is_valid": True, "flagged_amounts": [], "engine_amounts": [], "warning": None}
    
    # Collect all numeric values from engine output (recursively)
    engine_amounts = set()
    _collect_numeric_values(engine_output, engine_amounts)
    
    # Check each AI amount against engine amounts
    flagged = []
    for amount in ai_amounts:
        # Skip very small amounts (likely not tax figures)
        if amount < 100:
            continue
        
        # Check if this amount matches any engine value within tolerance
        matched = any(abs(amount - eng_val) <= tolerance for eng_val in engine_amounts)
        if not matched:
            flagged.append(amount)
    
    is_valid = len(flagged) == 0
    
    warning = None
    if not is_valid:
        flagged_str = ", ".join(f"₹{a:,.0f}" for a in flagged)
        warning = (
            f"VALIDATION FAILED: AI response contains figures not from the tax engine: "
            f"{flagged_str}. These may be hallucinated. All tax figures must come from "
            f"the deterministic engine."
        )
    
    return {
        "is_valid": is_valid,
        "flagged_amounts": flagged,
        "engine_amounts": sorted(engine_amounts),
        "warning": warning
    }


def _collect_numeric_values(obj: Any, values: set):
    """Recursively collect all numeric values from a dict/list structure."""
    if isinstance(obj, dict):
        for v in obj.values():
            _collect_numeric_values(v, values)
    elif isinstance(obj, list):
        for item in obj:
            _collect_numeric_values(item, values)
    elif isinstance(obj, (int, float)):
        if obj != 0:
            values.add(float(obj))


def sanitize_response(ai_text: str, engine_output: Dict[str, Any]) -> str:
    """
    If validation fails, append a disclaimer to the AI response.
    Does NOT modify the text content — just adds a warning footer.
    
    In production, this could strip or replace unauthorized figures.
    """
    result = validate_response(ai_text, engine_output)
    
    if result["is_valid"]:
        return ai_text
    
    disclaimer = (
        "\n\n⚠️ Note: Some figures in this response could not be verified "
        "against the tax engine. Please refer to the calculation breakdown "
        "above for authoritative tax figures."
    )
    return ai_text + disclaimer
